language: python
python:
    - "3.6"
before_install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
install:
  - pip install -qr requirements.txt
script: pytest --cov=src
after_success:
    - coveralls
